### ISSUE TITLE
Actual LKP addon

### ISSUE THREAD

**Issue by dogtopus** [Project-Alpaca/GP2040-CE#3]
Continuation of #2

- [x] Refactor out the hardcoded parts as config options.
- [x] Avoid BitBang_I2C as it's properly declared deprecated.
- [x] Refactor I2C peek/pokes so DRY while stay reasonably efficient.
  - [x] Project-Alpaca/LKP-FW#4
- [x] Project-Alpaca/LKP-FW#5
- [x] Project-Alpaca/LKP-FW#6
- [x] Add new options to WebUI.
- [x] Add default values for options to Storage (needs research).
